export const FI_TEST_ACCESS_TOKEN = `eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBVExfUm9tYW4iLCJyb2x
                                    lcyI6WyJST0xFX0FETUlOIiwiUk9MRV9BUEkiLCJST0xFX1VTRVIiX
                                    SwiaXNzIjoiU3ByaW5nIFNlY3VyaXR5IFJFU1QgR3JhaWxzIFBsdWdp
                                    biIsImV4cCI6MTYyNzgzMjE5OSwiaWF0IjoxNjI3ODI4NTk5fQ.HPtD
                                    MX5fzWUR2t-60n62kyE7R99KE98kYdsBTm9z8dk`;